#!/usr/bin/env zsh

CS="\033[1;30m"
CR="\033[1;31m"
CG="\033[1;32m"
CB="\033[1;34m"
CC="\033[1;36m"
CD="\033[0m"
HOMEBREW_ROOT="/usr/local"
if [ $(arch) = arm64 ]; then
  HOMEBREW_ROOT="/opt/homebrew"
fi

BINARIES=(
  bash
  colima
  diff-so-fancy
  docker
  docker-compose
  dust
  duti
  git
  htop
  httpie
  jq
  libpq
  m1ddc
  nano
  openjdk
  pyenv
  pyenv-virtualenv
  rename
  svn
  tldr
  tree
  watch
  zlib
  zsh
  zsh-autosuggestions
  zsh-syntax-highlighting
  koekeishiya/formulae/skhd
  koekeishiya/formulae/yabai
)

APPLICATIONS=(
  alt-tab
  betterdisplay
  bitwarden
  datagrip
  dropbox
  firefox
  fleet
  font-source-code-pro
  font-source-sans-pro
  freecad
  github
  google-chrome
  iina
  intellij-idea
  iterm2
  krita
  obsidian
  pycharm
  skype
  stats
  sublime-text
  transmission
  visual-studio-code
  xquartz
)

PYTHONS=(
  3.11.6
  3.12.0
)


function help () {
  print ""
  print "Usage: osm COMMAND [OPTIONS]"
  print ""
  print "OSM is a tool for managing OS binaries and applications"
  print ""
  print "Common Commands:"
  print "  install  Install dependencies"
  print "  update   Install or update binaries and applications"
  print ""
}

function install () {
  print "${CS}Started on $(date "+%F %T")${CD}"

  print ""
  print "${CB}» Installing xcode${CD}"
  if [ ! $(command -v xcode-select) ]; then
    xcode-select --install || true
  fi

  print ""
  print "${CB}» Installing brew${CD}"
  if [ ! $(command -v brew) ]; then
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh > /tmp/brew.installer && /bin/bash /tmp/brew.installer || true
  fi

  print ""
  print "${CS}Finished on $(date "+%F %T")${CD}"
}

function update () { 
  print "${CS}Started on $(date "+%F %T")${CD}"

  print ""
  print "${CB}» Updating brew${CD}"
  brew tap homebrew/cask-fonts
  brew tap homebrew/cask-versions
  brew update
  brew upgrade

  print ""
  print "${CB}» Updating binaries${CD}"
  for binary in ${BINARIES[@]}; do
    brew install $binary
  done

  print ""
  print "${CB}» Updating applications${CD}"
  for application in ${APPLICATIONS[@]}; do
    location="${HOMEBREW_ROOT}/Caskroom/"${application}"/.metadata/"
    if [ ! -d ${location} ]; then
      print "${application} is missing, installing"
      brew install --cask ${application}
      continue
    fi
    current=$(ls -t ${location} | grep -v "config.json" | head -n 1)
    newest=$(brew info --cask ${application} | head -n 1 | cut -d " " -f 3)
    if [ ${current} != ${newest} ]; then
      read "action?${application} out of date. Update ${current} > ${newest}? [Y|n]: "
      if [ ${action:-Y} = "Y" ]; then
        brew uninstall --cask ${application} --force
        brew install --cask ${application}
      fi
      continue
    fi
    print "${application} is up to date"
  done

  print ""
  print "${CB}» Installing python${CD}"
  for python in ${PYTHONS[@]}; do
    print "  ${CC}${python}${CD}"
    pyenv install ${python} --skip-existing
  done

  print ""
  print "${CB}» Cleanup brew${CD}"
  brew cleanup -s
  brew autoremove
  brew doctor || true

  print ""
  print "${CS}Finished on $(date "+%F %T")${CD}"
}


if [[ $1 =~ ^(help|install|update)$ ]]; then
  "$@"
  exit 1
fi

help
